### ISSUE TITLE
Restarting Gnome Shell kicks out users running playbook against localhost

### ISSUE THREAD

**Issue by Aidenwebb** [PeterMosmans/ansible-role-customize-gnome#29] opened 2023-05-03 18:48 UTC
Not all Gnome Extensions require a restart of the Gnome Shell

When running against the local system, the `Restart Gnome Shell to ensure all extensions are visible` task will kick the user out and halt execution of ansible.

Adding a variable to skip this step if it is unwanted would resolve this problem.

**Comment by grdryn** [comment] 2023-05-10 15:35
I've hit this too. I think the problem is that GNOME Shell on Wayland doesn't have a concept of "restart", so the current session gets killed, and the user is dropped back to the login screen.

What I've also seen is that some extensions seem to always cause the "unzip extension" task to be marked as changed, so even if they're up-to-date, this problem is hit.

@PeterMosmans out of curiosity, do you use GNOME on Wayland or X11?

**Comment by PeterMosmans** [comment] 2023-05-15 18:25
Apologies for my late replies, it's been kinda *busy*
For myself @grdryn , I currently don't use this playbook, but I do test it with X11, hence probably the problem. To be continued :)

**Closed** 2023-09-28 19:30 UTC
